version: '3'

networks:
  dbnetwork:
  tasknetwork:

volumes:
  pg_data:
  redis_data:

services:

  db:
    image: postgres:latest
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dbnetwork
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:3.2.0
    networks:
      - tasknetwork
    volumes:
      - redis_data:/data
    command: redis-server

  tem-api:
    build: .
    image: tem-api:latest
    command: sh runserver.sh
    networks:
      - dbnetwork
    ports:
      - 3333:3333
    expose:
      - 3333
    volumes:
      - ./src:/opt/tem-api
    depends_on:
      - db
      - redis
  
  celery:
    image: tem-api:latest
    networks:
      - dbnetwork
      - tasknetwork
    environment:
      - CELERY_BROKER_URL=redis://redis
    volumes:
      - ./src:/opt/tem-api
    command: celery worker -A djreact -B -l info
    depends_on:
      - tem-api
      - redis
      - db
